### ISSUE TITLE
Walkthrough Videos Set to Private

### ISSUE THREAD

**Issue by SeanPrashad** [humphd/ng-bridge#1]
Currently, all videos in the `README` are set to private on YouTube.

You might also find value from adding timestamps to create [_YouTube Chapters_](https://www.youtube.com/watch?v=b1Fo_M_tj6w&feature=emb_title), an easy way for students to see a breakdown of the video by hovering over the timeline:

<img width="844" alt="Screen Shot 2020-07-03 at 7 02 36 PM" src="https://user-images.githubusercontent.com/13009507/86500531-c3a2f180-bd5f-11ea-87fc-4f32c893158b.png">

**Comment by humphd** [comment]
Nothing gets past you, does it :) ?

I set them to go public on Sunday morning, because I have like 8 videos I needed to be fully rendered in HD by Monday, and didn't want to have them appear until they were available in high quality.

I'll have to look into chapters, I've never used them.

I'll leave this open until I'm sure that the video URLs do in fact work.

**Comment by humphd** [comment]
Looks like all these URLs are all working now, closing.
